-- 코드를 입력하세요
SELECT ICECREAM_INFO.FLAVOR from ICECREAM_INFO inner join FIRST_HALF
where ICECREAM_INFO.FLAVOR = FIRST_HALF.FLAVOR
    and FIRST_HALF.TOTAL_ORDER > 3000
    and ICECREAM_INFO.INGREDIENT_TYPE like 'fruit_based'
order by FIRST_HALF.TOTAL_ORDER desc;