SELECT
    C.CAR_ID,
    C.CAR_TYPE,
    ROUND(C.DAILY_FEE * 30 * (100 - cp.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN cp 
    ON c.CAR_TYPE = cp.CAR_TYPE
    AND cp.DURATION_TYPE = '30일 이상'
WHERE c.CAR_TYPE IN ('세단', 'SUV')
    AND c.CAR_ID NOT IN (
        SELECT ch1.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY ch1
        WHERE ch1.START_DATE <= '2022-11-30'
          AND ch1.END_DATE >= '2022-11-01'
    )
    AND ROUND(C.DAILY_FEE * 30 * (100 - cp.DISCOUNT_RATE) / 100)
        BETWEEN 500000 AND 1999999
ORDER BY
    FEE DESC,
    C.CAR_TYPE ASC,
    C.CAR_ID DESC;